services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    ports:
      - "8191:8191"
    environment:
      LOG_LEVEL: info
      MAX_CONCURRENT_SESSIONS: 5
      TIMEOUT: 30000
    volumes:
      - /etc/localtime:/etc/localtime:ro